/**
 * legal-privacy.mjs — /legal/privacy
 *
 * A COMPLETE DRAFT with the product facts filled in and every legal
 * determination flagged. Not legal advice, and not to go live without a named
 * lawyer's sign-off — see the standing caveat in src/lib/legal.mjs.
 *
 * TWO AUDIENCES WITH GENUINELY DIFFERENT CONCERNS, so the document leads with a
 * chooser and is ordered CANDIDATE FIRST. Most privacy policies in this category
 * fail candidates by writing entirely for the buyer.
 *
 * SECTION 3 IS THE ONE THAT MOST NEEDS TO EXIST AND IS THE MOST LIKELY TO BE
 * QUIETLY OMITTED: profiles a person did not create. `docs/phase-4.md` § 5.2 § 3
 * says so explicitly. It is not omitted.
 *
 * SECTION 4 IS WHERE THE PRODUCT IS UNUSUALLY STRONG. A privacy policy that
 * tells you the actual weights of the model that ranked you is a rare thing, and
 * the weights are read from the same data module the marketing pages read, so
 * this section cannot drift from /product/matching.
 */

import { audienceChooser, counsel, legalDoc } from '../lib/legal.mjs';
import { BANDS, DIMENSIONS, MODIFIERS, SIGNALS } from '../../assets/data/product-demo.js';

export const meta = {
  path: '/legal/privacy/',
  title: 'Privacy policy (draft) — Transpahire',
  description:
    'What Transpahire holds about a candidate, what it computes, who can see it, what an automated ranking is and is not, and what you can ask for. A complete draft, pending legal review.',
};

const pct = (d) => Math.round(d.weight * 100);

const SECTIONS = [
  {
    n: '1', id: 'who-we-are', title: 'Who we are',
    body: `        <p>
          Transpahire, Inc. operates the Transpahire platform: a recruitment product used by
          hiring organisations to find, rank and track candidates, and by candidates to build a
          profile, see how they score against roles and apply to them.
        </p>
        <p>
          ${counsel('Registered entity name, company number, registered address, and the address for privacy enquiries. Also whether a data protection officer, an EU representative or a UK representative is required, and if so who.')}
        </p>
        <p>
          For every purpose in this policy, the hiring organisation that holds a candidate in its
          own pool and the platform have different roles in respect of the same data.
          ${counsel('The controller / joint controller / processor determination, per category of processing. This is the determination the rest of the document depends on and it should be made first.')}
        </p>`,
  },
  {
    n: '2', id: 'candidate-data', title: 'What we hold about a candidate',
    body: `        <p>
          This section is complete, because the product can answer it completely. It is split by
          where the data came from, because that is the distinction that decides what you can do
          about it.
        </p>

        <h3>Given by you</h3>
        <p>
          Name, email address, phone number, location, headline, summary, links, work history,
          education, projects, certifications, languages, and skills with a self-rated
          proficiency and a number of years against each. Then your preferences: salary
          expectation, preferred location, notice period, work style, and whether you are open to
          work.
        </p>

        <h3>Extracted from a résumé you upload</h3>
        <p>
          The same fields, each with a confidence indicator, and <strong>each shown to you to
          accept, reject or edit before anything is stored</strong>. The uploaded file itself is
          retained as a document on your profile.
          ${counsel('Retention period for the original uploaded file, which is a different decision from the retention period for the extracted fields.')}
        </p>

        <h3>Generated by the platform</h3>
        <ul>
          <li>A match score per role, out of 100, with its per-dimension breakdown, its per-skill
            coverage, and the classification it fell into.</li>
          <li>A résumé quality score, with specific suggestions.</li>
          <li>Profile completeness.</li>
          <li>Four inferences: ${SIGNALS.map((s) => s.label.toLowerCase()).join(', ')} risk.</li>
          <li>Detected gaps in your work history, recorded as a property of the timeline.</li>
          <li>A numeric representation of your profile, used to find profiles that are similar to
            a described requirement. It is not human-readable and it is not shared.</li>
        </ul>

        <h3>Recorded as you use the platform</h3>
        <p>
          Applications and their stage history, saved jobs, saved searches, job alerts, profile
          views by recruiters, and outreach you received together with how you responded to it.
        </p>

        <h3>Held by an organisation about you</h3>
        <p>
          An organisation that has you in its pool holds its own record of you: their stage for
          you, their notes, tags and rating, and the source by which you entered their pool. That
          record is theirs and is not visible to another organisation.
          ${counsel('What happens to an organisation’s own notes about a candidate after that candidate deletes their account. This is the single most consequential retention question in the document.')}
        </p>`,
  },
  {
    n: '3', id: 'unclaimed', title: 'Profiles you did not create',
    body: `        <p>
          <strong>Not every profile on Transpahire was made by the person it describes.</strong> A
          recruiter can add somebody to their own organisation&rsquo;s pool from a list they
          already had — a spreadsheet, a CSV, a referral, a profile they found elsewhere. This
          section exists because that is true, and because a policy that only describes people who
          signed up is describing half the database.
        </p>

        <h3>What such a profile contains</h3>
        <p>
          Whatever the importing organisation supplied, and whatever was extracted from a document
          they supplied: typically a name, contact details, a work history and a set of skills.
          The same fields as any other profile, from a different source.
        </p>

        <h3>Who can see it</h3>
        <p>
          Only the organisation that imported it, until the person takes it over. It is not
          visible to other organisations, it is not part of the wider marketplace, and it does not
          appear in another employer&rsquo;s search results.
        </p>

        <h3>How it is marked</h3>
        <p>
          Every profile carries an account status, and it is shown on the candidate card the
          recruiter is looking at: <em>unclaimed</em>, <em>invited</em>, <em>activated</em>,
          <em>verified</em> or <em>opted out</em>. A recruiter always knows whether they are
          looking at somebody who chose to be there.
        </p>

        <h3>How to claim it, or leave</h3>
        <p>
          An invitation to claim a profile is sent to the contact address on it, and claiming it
          makes it yours: your visibility settings, your edits, your export and deletion rights.
          Opting out marks the profile opted out and removes it from search.
          ${counsel('The lawful basis for holding an unclaimed imported profile, per jurisdiction, and the notification obligation and its timing. Whether an invitation must be sent, and within what period, rather than being available to send.')}
        </p>
        <p>
          ${counsel('The allocation of responsibility between the importing organisation and the platform for the lawfulness of the import itself. This most likely also belongs in a data processing agreement.')}
        </p>`,
  },
  {
    n: '4', id: 'automated', title: 'Automated decision-making, and what the score is',
    body: `        <p>
          The platform computes a recommendation and a ranking. <strong>It does not make hiring
          decisions.</strong> A person at the hiring organisation reads the reasoning and decides,
          and the responsibility for that decision is theirs.
        </p>

        <h3>What goes into the score</h3>
        <p>
          Four weighted factors:
        </p>
        <ul>
${DIMENSIONS.map((d) => `          <li><strong>${d.label}</strong> — ${pct(d)}% of the weighted score.</li>`).join('\n')}
        </ul>
        <p>
          Three modifiers, applied after the weighted score, in this order:
        </p>
        <ul>
${MODIFIERS.map((m) => `          <li><strong>${m.label}</strong> (${m.shape}) — ${m.note.toLowerCase()}</li>`).join('\n')}
        </ul>
        <p>
          And one disqualifying gate: a candidate who does not meet a requirement the organisation
          marked <em>critical</em> is excluded before scoring. Which requirement excluded them is
          recorded.
        </p>
        <p>
          The result is classified
          ${BANDS.map((b) => `<strong>${b.label}</strong>${b.min ? ` (from ${b.min})` : ' (below that)'}`).join(', ')}.
          We publish these figures here as well as on the product pages, because a policy that
          tells you the model is "proprietary" has told you nothing.
        </p>

        <h3>What is stored with it</h3>
        <p>
          Every score is stored together with the weights in force at the time, the per-skill
          scores, and the verdict. A result can therefore be reconstructed as it was, rather than
          re-run under a later model.
        </p>

        <h3>What is not used</h3>
        <p>
          <strong>No demographic data is used, inferred or held.</strong> Not gender, age,
          ethnicity, religion, disability, or a proxy for any of them. There is no field for it.
        </p>
        <p>
          The platform separately reports to a hiring organisation on how the requirements in
          their own job description narrow the candidate pool — flagging exclusionary language and
          requirement lists almost nobody clears. That report reads the job description, not the
          candidates, and it uses no demographic data either.
        </p>

        <h3>What you can ask for</h3>
        <ul>
          <li>The reasoning behind a score. The breakdown a recruiter sees is the breakdown you
            see, including the parts that count against you.</li>
          <li>Correction of the underlying data, which you can do directly on your profile.</li>
          <li>Human review of a decision taken about you.</li>
        </ul>
        <p>
          ${counsel('The exact rights language per jurisdiction, and the threshold question: whether a ranking that a person then acts on constitutes a "decision based solely on automated processing" under Article 22 GDPR, the UK equivalent, and the Indian DPDP Act. Also whether any of the four inferences is special category data or a profiling activity requiring its own notice.')}
        </p>`,
  },
  {
    n: '5', id: 'visibility', title: 'Visibility, and who can see you',
    body: `        <p>
          A candidate profile has three visibility levels, set by the candidate: <strong>public</strong>,
          <strong>limited</strong> and <strong>private</strong>. They control whether an
          organisation that did not source you can find you at all.
        </p>
        <p>
          ${counsel('Verify the exact behaviour of each of the three levels against the product before publishing this section. The site must not describe a control the product does not have, and a visibility level described one degree stronger than it is would be the worst single error in this document.')}
        </p>
        <p>
          Separately from visibility: access inside an organisation is limited by role and by job
          assignment. A recruiter who is not assigned to a job does not get a partial view of its
          candidates — the request is refused. Organisations are isolated from each other.
        </p>`,
  },
  {
    n: '6', id: 'rights', title: 'Your rights',
    body: `        <p>
          Access, correction, export, deletion, objection, and withdrawal of consent.
        </p>
        <p>
          <strong>Export and deletion are live routes in the product</strong>, not an address to
          write to. A request is raised in the platform, enters a review queue, and is completed —
          and the completion is itself a logged event.
          ${counsel('The response deadline to state, per jurisdiction, and the identity-verification step required before a deletion is actioned.')}
        </p>
        <p>
          ${counsel('The complaints route: the supervisory authority or authorities to name, and the internal escalation before it.')}
        </p>`,
  },
  {
    n: '7', id: 'retention', title: 'Retention',
    body: `        <p>
          ${counsel('This section needs a decision per data class and cannot be drafted without one. At minimum it needs a stated position on each of: an inactive candidate profile; an unclaimed imported profile that is never claimed; an uploaded résumé file; match scores and the audit records attached to them; search audit logs; and an organisation’s own notes about a candidate after that candidate deletes their account.')}
        </p>
        <p>
          What can be said today: match scores and audit records are retained deliberately rather
          than incidentally, because a score that cannot be reconstructed cannot be questioned.
          That is a reason to keep them, and it is not a reason to keep them indefinitely.
        </p>`,
  },
  {
    n: '8', id: 'processors', title: 'Sub-processors and transfers',
    body: `        <p>
          A named list is worth more than a paragraph about trusted partners. Known from the
          product today, and to be confirmed and completed:
        </p>
        <ul>
          <li>An AI inference provider, used to generate match explanations and résumé critiques.
            Every call is logged.</li>
          <li>Object storage, for uploaded résumés and organisation logos.</li>
          <li>An email delivery provider, for notifications and invitations.</li>
          <li>A company-logo lookup service, used as a fallback when an organisation has not
            uploaded a logo.</li>
        </ul>
        <p>
          ${counsel('The actual sub-processor list with each entity named, its purpose, its location, and the transfer mechanism relied on for each. Also whether any of them may use data passed to them for their own training, which for the inference provider is the question a candidate would most want answered.')}
        </p>`,
  },
  {
    n: '9', id: 'cookies', title: 'Cookies',
    body: `        <p>
          The marketing site and the application are different cases and are described separately
          in the <a href="/legal/cookies/">cookie policy</a>. In short: this site sets no cookies,
          and the application sets the ones a login needs.
        </p>`,
  },
  {
    n: '10', id: 'contact', title: 'Contact',
    body: `        <p>
          A named address, not a form. If you are a candidate with a question about data
          Transpahire holds about you, that address is the route.
          ${counsel('The address, and the person or role behind it.')}
        </p>`,
  },
  {
    n: '11', id: 'changes', title: 'Changes to this policy',
    body: `        <p>
          When this document is signed off it gets a version and a date, and every subsequent
          change gets its own. A material change is notified to registered users rather than
          published silently.
          ${counsel('What counts as material, and the notification period.')}
        </p>`,
  },
];

export function render() {
  return legalDoc({
    eyebrow: 'Privacy policy',
    title: 'Privacy policy',
    lede: 'What the platform holds about you, what it computes, who can see it, and what you can ask for. Including the actual weights of the model that ranks you.',
    chooser: audienceChooser({
      candidateHref: '#candidate-data',
      orgHref: '/legal/terms/organisations/',
      note: 'This document is ordered candidate-first, on purpose. Organisations should also read the organisation terms, which cover what you may do with candidate data you reach through search.',
    }),
    sections: SECTIONS,
  });
}
