/**
 * build.mjs — assembles the static site.
 *
 * WHAT THIS IS, AND WHAT IT IS NOT.
 *
 * The shipped site is still plain HTML, CSS and native ES modules: no runtime
 * dependency, no framework, nothing to install to view it. This script is an
 * AUTHORING TOOL that runs on the maintainer's machine and writes the HTML
 * files that get served. It uses only Node's standard library — the project's
 * dependency count remains zero.
 *
 * Why it exists. `docs/architecture.md § 1` sets the migration trigger at two
 * or more of: more than three pages · a committed blog · data-driven product
 * visualisations · non-maintainer editors. Two fire:
 *
 *   · Thirteen pages. Thirteen hand-maintained copies of a <head>, a header, a
 *     drawer and a footer is exactly the rot that trigger exists to prevent,
 *     and the drift is invisible until one page has a link the other twelve do
 *     not.
 *
 *   · Data-driven compositions. `08 § 1` is explicit and non-negotiable:
 *     "Numbers appear once. 87 appears in sections 01, 05, 06, 08 and 10. That
 *     is one value read five times. Hand-typing it guarantees divergence, and a
 *     divergence here is the most visible possible defect." Across ten pages
 *     that value is read more than twenty times.
 *
 * Astro remains the planned target (`docs/architecture.md § 1`), and this does
 * not replace it. It is the smallest thing that satisfies the two triggers
 * without adding a dependency, a lockfile or a runtime: every page module is a
 * function returning a string, which is what an `.astro` component is with
 * different syntax, so the eventual port stays mechanical.
 *
 * Run:  node tools/build.mjs
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { document_ } from '../src/lib/layout.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Every page, in navigation order. Twenty-three as of Phase 5: Phase 4's
 * twenty-one plus the two tool pages, which are the site's first and only
 * low-threshold conversion path (`docs/phase-5.md` § 4).
 *
 * The sitemap is generated from this list, so a page cannot be added without
 * appearing in it — which is also why tools/check.mjs derives its own list from
 * the built files rather than holding a third copy.
 */
const PAGES = [
  'home',
  'product',
  'product-matching',
  'product-sourcing',
  'product-candidate-intelligence',
  'product-hiring-operations',
  'product-analytics',
  'for-teams',
  'for-hiring-managers',
  'for-candidates',
  'trust',
  'pricing',
  'changelog',
  'check-job-description',
  'check-resume',
  'demo',
  'about',
  'legal-index',
  'legal-privacy',
  'legal-terms',
  'legal-terms-organisations',
  'legal-terms-candidates',
  'legal-cookies',
];

/** '/' → index.html · '/product/matching/' → product/matching/index.html */
function fileFor(path) {
  if (path === '/') return 'index.html';
  return join(path.replace(/^\/|\/$/g, ''), 'index.html');
}

const written = [];

for (const name of PAGES) {
  const module = await import(`../src/pages/${name}.mjs`);
  const { meta, render } = module;

  if (!meta?.path || !meta.title || !meta.description) {
    throw new Error(`${name}.mjs is missing meta.path, meta.title or meta.description`);
  }

  const html = document_({
    path: meta.path,
    title: meta.title,
    description: meta.description,
    body: render(),
  });

  const file = join(ROOT, fileFor(meta.path));
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, html);
  written.push({ path: meta.path, file: fileFor(meta.path), bytes: html.length });
}

/* --------------------------------------------------------------------------
   sitemap.xml — generated from the same list, so a new page cannot be added
   without appearing in it. Kept accurate even while the site is noindex: the
   day the integrity gate clears, this file is already right.
   -------------------------------------------------------------------------- */

const SITE = 'https://transpahire.com';
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by tools/build.mjs from the page list. Do not edit by hand.

  The site is currently closed to search engines on purpose: robots.txt
  disallows everything and every page carries meta robots noindex. This sitemap
  is therefore accurate and inert. Opening the site requires clearing the
  content inventory first — docs/content-integrity.md § 5, and robots.txt itself
  lists the six outstanding blockers with their owners.
-->
<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">
${written.map((p) => `  <url><loc>${SITE}${p.path}</loc></url>`).join('\n')}
</urlset>
`.replace('www.sitemap.org', 'www.sitemaps.org');

writeFileSync(join(ROOT, 'sitemap.xml'), sitemap);

/* --------------------------------------------------------------------------
   Report
   -------------------------------------------------------------------------- */

const total = written.reduce((sum, p) => sum + p.bytes, 0);
console.log(`${written.length} pages, ${(total / 1024).toFixed(0)}KB total\n`);
for (const p of written) {
  console.log(`  ${(p.bytes / 1024).toFixed(1).padStart(6)}KB  ${p.file}`);
}

/* A cheap guard against the one defect `08 § 1` names as the most visible
   possible: the worked example's score diverging between pages. */
const { candidate } = await import('../assets/data/product-demo.js');
const expected = String(candidate('c1').score);
const offenders = written
  .map((p) => {
    const html = readFileSync(join(ROOT, p.file), 'utf8');
    const scores = [...html.matchAll(/data-count="(\d+)"/g)].map((m) => m[1]);
    return { file: p.file, scores };
  })
  .filter((p) => p.scores.length && !p.scores.includes(expected) && p.file !== 'index.html');

console.log(`\nworked-example score: ${expected}`);
if (offenders.length) {
  console.log('pages with counters but no reference to it (check intentional):');
  offenders.forEach((p) => console.log(`  ${p.file} → ${p.scores.join(', ')}`));
}
